### ISSUE TITLE
Separate nuget package?

### ISSUE THREAD

**Issue by OlegGavrilov** [vtr-dev/HubSpot.NET#1]
Since this fork has progressed much more than the original squaredup repo, maybe it is worth it to publish it as a separate nuget package? Maybe on myget?

**Comment by Psypher9** [comment]
I do agree and we have plans to release it. We haven't been able to fully test it out yet though so we aren't quite ready for it. Luckily though, we are doing a major test of key components tomorrow. Thank you for your interest!
